version: '2.3'
services:
  test-cpu-base:
    build:
      context: .
      dockerfile: Dockerfile.test.cpu
    privileged: true
  test-cpu-openmpi-py2.7-tf1.1.0-keras2.0.0-torch0.4.0-pyspark2.1.2:
    extends: test-cpu-base
    build:
      args:
        DEBIAN_VERSION: jessie
        MPI_KIND: OpenMPI
        PYTHON_VERSION: 2.7
        TENSORFLOW_PACKAGE: tensorflow==1.1.0
        KERAS_PACKAGE: keras==2.0.0
        PYTORCH_PACKAGE: torch==0.4.0
        PYSPARK_PACKAGE: pyspark==2.1.2
  test-cpu-openmpi-py3.5-tf1.1.0-keras2.0.0-torch0.4.0-pyspark2.1.2:
    extends: test-cpu-base
    build:
      args:
        DEBIAN_VERSION: stretch
        MPI_KIND: OpenMPI
        PYTHON_VERSION: 3.5
        TENSORFLOW_PACKAGE: tensorflow==1.1.0
        KERAS_PACKAGE: keras==2.0.0
        PYTORCH_PACKAGE: torch==0.4.0
        PYSPARK_PACKAGE: pyspark==2.1.2
  test-cpu-openmpi-py3.6-tf1.1.0-keras2.0.0-torch0.4.0-pyspark2.1.2:
    extends: test-cpu-base
    build:
      args:
        DEBIAN_VERSION: buster
        MPI_KIND: OpenMPI
        PYTHON_VERSION: 3.6
        TENSORFLOW_PACKAGE: tensorflow==1.1.0
        KERAS_PACKAGE: keras==2.0.0
        PYTORCH_PACKAGE: torch==0.4.0
        PYSPARK_PACKAGE: pyspark==2.1.2
  nvidia-smi:
    image: nvidia/cuda
    runtime: nvidia
    command: nvidia-smi
