version: '2.3'
services:
  test-cpu-base:
    build:
      context: .
      dockerfile: Dockerfile.test.cpu
    privileged: true
  test-cpu-openmpi-py2_7-tf1_1_0-keras2_0_0-torch0_4_0-pyspark2_1_2:
    extends: test-cpu-base
    build:
      args:
        DEBIAN_VERSION: jessie
        MPI_KIND: OpenMPI
        PYTHON_VERSION: 2.7
        TENSORFLOW_PACKAGE: tensorflow==1.1.0
        KERAS_PACKAGE: keras==2.0.0
        PYTORCH_PACKAGE: torch==0.4.0
        PYSPARK_PACKAGE: pyspark==2.1.2
  test-cpu-openmpi-py3_5-tf1_1_0-keras2_0_0-torch0_4_0-pyspark2_1_2:
    extends: test-cpu-base
    build:
      args:
        DEBIAN_VERSION: stretch
        MPI_KIND: OpenMPI
        PYTHON_VERSION: 3.5
        TENSORFLOW_PACKAGE: tensorflow==1.1.0
        KERAS_PACKAGE: keras==2.0.0
        PYTORCH_PACKAGE: torch==0.4.0
        PYSPARK_PACKAGE: pyspark==2.1.2
  test-cpu-openmpi-py3_6-tf1_1_0-keras2_0_0-torch0_4_0-pyspark2_1_2:
    extends: test-cpu-base
    build:
      args:
        DEBIAN_VERSION: buster
        MPI_KIND: OpenMPI
        PYTHON_VERSION: 3.6
        TENSORFLOW_PACKAGE: tensorflow==1.1.0
        KERAS_PACKAGE: keras==2.0.0
        PYTORCH_PACKAGE: torch==0.4.0
        PYSPARK_PACKAGE: pyspark==2.1.2
  # TODO: shows how to use GPUs
  nvidia-smi:
    image: nvidia/cuda
    runtime: nvidia
    command: nvidia-smi
